apiVersion: v1
kind: Secret
metadata:
  name: vinyl-spins-postgres
  namespace: vinyl-spins
type: Opaque
stringData:
  POSTGRES_USER: "discogs"
  POSTGRES_PASSWORD: "discogs"
  POSTGRES_DB: "discogs_listen_tracker"

